# Generated by Django 3.2.6 on 2021-08-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
